spring.application.name=lost-found-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lost_found_db
spring.datasource.username=vars3
spring.datasource.password=slf1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.server.port=8080